pipeline {
    agent any

    stages {                
        
       stage ('Build') {
         steps {
               sh 'mvn clean install -f myJan2021Repo/MyWebApp/pom.xml'
            }           
        }   
        post {
                always {
                    junit 'target/surefire-reports/*.xml'
                }
            }
    
            stage ('Nexus upload') {
                steps {
                              nexusArtifactUploader artifacts: [[artifactId: 'MyWebApp', classifier: '', file: 'myJan2021Repo/MyWebApp/target/MyWebApp.war', type: 'war']], credentialsId: 'Nexus', groupId: 'com.dept.app', nexusUrl: '10.0.0.4:8081', nexusVersion: 'nexus3', protocol: 'http', repository: 'maven-snapshots', version: '1.0-SNAPSHOT'
 
                }
        
            }
        
    } 
    post { 
        always { 
            echo 'I will always say Hello!'
              mail to: 'pl.shivashankar@gmail.com',
            subject: "Failed Pipeline: ${currentBuild.fullDisplayName}",
            body: "Something is wrong with ${env.BUILD_URL}"
        }
        aborted {
            echo 'I was aborted'
              mail to: 'pl.shivashankar@gmail.com',
            subject: "Failed Pipeline: ${currentBuild.fullDisplayName}",
            body: "Something is wrong with ${env.BUILD_URL}"
        }
        failure {
            mail to: 'pl.shivashankar@gmail.com',
            subject: "Failed Pipeline: ${currentBuild.fullDisplayName}",
            body: "Something is wrong with ${env.BUILD_URL}"
        }
    }
    
}
