pipeline {
    agent any

    stages {                
        
       stage ('Build') {
         steps {
               sh 'mvn clean install -f myJan2021Repo/MyWebApp/pom.xml'
            }           
        }              
    
            stage ('Nexus upload') {
                steps {
                              nexusArtifactUploader artifacts: [[artifactId: 'MyWebApp', classifier: '', file: 'myJan2021Repo/MyWebApp/target/MyWebApp.war', type: 'war']], credentialsId: 'Nexus', groupId: 'com.dept.app', nexusUrl: '10.0.0.4:8081', nexusVersion: 'nexus3', protocol: 'http', repository: 'maven-snapshots', version: '1.0-SNAPSHOT'
 
                }
        
            }
        
    }    
    
}
